global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.20.131:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['192.168.20.131:15692']

  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: ['192.168.20.131:9000']

  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.20.128  # Proxmox VE node.
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.20.128:9221  # PVE exporter.