global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.20.131:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['192.168.20.131:15672']

  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: ['192.168.20.131:9000']

  - job_name: 'proxmox'
    static_configs:
      - targets: ['192.168.20.128:9221']  # Replace <proxmox-host> with the Proxmox host's IP or hostname
